# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('test1_rcpp_hello_world', PACKAGE = 'test1')
}

rcpp_hello_world2 <- function() {
    .Call('test1_rcpp_hello_world2', PACKAGE = 'test1')
}

make_mat <- function(r, c) {
    .Call('test1_make_mat', PACKAGE = 'test1', r, c)
}

frate_counts <- function(spikes, beg, end, wid, nbins) {
    .Call('test1_frate_counts', PACKAGE = 'test1', spikes, beg, end, wid, nbins)
}

#' 
make_mat1 <- function(r, c) {
    .Call('test1_make_mat1', PACKAGE = 'test1', r, c)
}

run_Pcpp <- function(dt, spike_times_1, spike_times_2) {
    .Call('test1_run_Pcpp', PACKAGE = 'test1', dt, spike_times_1, spike_times_2)
}

heaviside_thetacpp <- function(x) {
    .Call('test1_heaviside_thetacpp', PACKAGE = 'test1', x)
}

run_Tcpp <- function(dt, start, end, spike_times_1) {
    .Call('test1_run_Tcpp', PACKAGE = 'test1', dt, start, end, spike_times_1)
}

run_TMcpp <- function(dt, start, end, spike_times_1, spike_times_2) {
    .Call('test1_run_TMcpp', PACKAGE = 'test1', dt, start, end, spike_times_1, spike_times_2)
}

tiling_arrcpp <- function(spikes, n, nspikes, first_spike, start, end, dt) {
    .Call('test1_tiling_arrcpp', PACKAGE = 'test1', spikes, n, nspikes, first_spike, start, end, dt)
}

tiling_correlogramcpp <- function(spikes, n, nspikes, first_spike, start, end, dt, tau_sep, tau_max) {
    .Call('test1_tiling_correlogramcpp', PACKAGE = 'test1', spikes, n, nspikes, first_spike, start, end, dt, tau_sep, tau_max)
}

tiling_correlogramcpp_index <- function(spikes, n, nspikes, first_spike, start, end, dt, tau_sep, tau_max, a, b) {
    .Call('test1_tiling_correlogramcpp_index', PACKAGE = 'test1', spikes, n, nspikes, first_spike, start, end, dt, tau_sep, tau_max, a, b)
}

sttc_allspikes1 <- function(spikes, dt, beg, end) {
    .Call('test1_sttc_allspikes1', PACKAGE = 'test1', spikes, dt, beg, end)
}

