# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_ns <- function(spikes, beg, end, wid, nbins) {
    .Call('test1_count_ns', PACKAGE = 'test1', spikes, beg, end, wid, nbins)
}

frate_counts <- function(spikes, beg, end, wid, nbins) {
    .Call('test1_frate_counts', PACKAGE = 'test1', spikes, beg, end, wid, nbins)
}

run_TMcpp <- function(dt, start, end, spike_times_1, spike_times_2) {
    .Call('test1_run_TMcpp', PACKAGE = 'test1', dt, start, end, spike_times_1, spike_times_2)
}

tiling_correlogramcpp <- function(spikes, n, nspikes, first_spike, start, end, dt, tau_sep, tau_max) {
    .Call('test1_tiling_correlogramcpp', PACKAGE = 'test1', spikes, n, nspikes, first_spike, start, end, dt, tau_sep, tau_max)
}

tiling_correlogramcpp_index <- function(spikes, n, nspikes, first_spike, start, end, dt, tau_sep, tau_max, a, b) {
    .Call('test1_tiling_correlogramcpp_index', PACKAGE = 'test1', spikes, n, nspikes, first_spike, start, end, dt, tau_sep, tau_max, a, b)
}

sttc_allspikes1 <- function(spikes, dt, beg, end) {
    .Call('test1_sttc_allspikes1', PACKAGE = 'test1', spikes, dt, beg, end)
}

sttcp_ab <- function(a, b, start, end, dt, tau_sep, tau_max) {
    .Call('test1_sttcp_ab', PACKAGE = 'test1', a, b, start, end, dt, tau_sep, tau_max)
}

